# Generated by Django 3.1.1 on 2021-01-07 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210106_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 16, 16, 21, 624659)),
        ),
        migrations.AlterField(
            model_name='cviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 16, 16, 21, 625660)),
        ),
    ]
