# Generated by Django 2.2.12 on 2020-05-30 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='image51862926581')),
                ('image2', models.ImageField(upload_to='image51862926581')),
                ('image3', models.ImageField(upload_to='image51862926581')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('computers', 'computers'), ('accessories', 'accessories'), ('printers', 'printers'), ('phones', 'phones')], max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.IntegerField()),
                ('pricebefore', models.IntegerField()),
                ('datepost', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-datepost'],
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('recommend', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
