# Generated by Django 2.2.12 on 2020-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('computers', 'computers'), ('laptops', 'laptops'), ('desktops', 'desktops'), ('accessories', 'accessories'), ('printers', 'printers'), ('phones', 'phones')], max_length=120),
        ),
    ]
