# Generated by Django 2.2.12 on 2020-06-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_shortdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
    ]
