# Generated by Django 3.0.3 on 2020-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_reviews_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('laptops', 'laptops'), ('desktops', 'desktops'), ('accessories', 'accessories'), ('printers', 'printers'), ('tvs', 'tvs')], max_length=120),
        ),
    ]
