# Generated by Django 3.0.8 on 2020-09-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200624_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image1',
            field=models.ImageField(help_text='width:255px,heigth:291px', upload_to='image51862926581'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image2',
            field=models.ImageField(help_text='width:255px,heigth:291px', upload_to='image51862926581'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image3',
            field=models.ImageField(help_text='width:255px,heigth:291px', upload_to='image51862926581'),
        ),
    ]
