# Generated by Django 3.0.8 on 2020-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200917_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('laptops', 'laptops'), ('desktops', 'desktops'), ('accessories', 'accessories'), ('printers', 'printers'), ('tvs', 'tvs'), ('others', 'others')], max_length=120),
        ),
    ]
