# Generated by Django 3.1.1 on 2020-11-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200917_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=50),
        ),
    ]
