# Generated by Django 3.1.1 on 2020-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_reviews_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image3',
        ),
        migrations.AlterField(
            model_name='shop',
            name='image2',
            field=models.ImageField(blank=True, help_text='width:255px,heigth:291px: this field can be blank', null=True, upload_to='image51862926581'),
        ),
    ]
