# Generated by Django 3.1.1 on 2020-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201219_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Ex uk', 'Ex uk')], default='New', max_length=100),
        ),
    ]
