# Generated by Django 3.1.1 on 2020-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shop_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instock',
            field=models.BooleanField(default=True),
        ),
    ]
