# Generated by Django 3.1.1 on 2020-12-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shop_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
